version: 2
jobs:
  build:
    docker:
      - image: openjdk:8
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      - run: ./gradlew clean build
  test:
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - run: ./gradlew test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test