version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: ./gradlew clean build
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: ./gradlew test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test